name: yemek_tarifi_app
description: "App For Food Recipes"
publish_to: 'none'
version: 2.7.0+27

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter 
  intl: ^0.20.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  multi_select_flutter: ^4.1.3
  dropdown_search: ^6.0.1
  font_awesome_flutter: ^10.12.0
  supabase_flutter: ^2.10.3
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  easy_localization: ^3.0.8
  animate_do: ^4.2.0
  google_mobile_ads: ^6.0.0
  app_links: ^6.4.1
  flutter_cache_manager: ^3.4.1
  share_plus: ^12.0.1
  package_info_plus: ^8.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:   
  generate: true
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/splash_logo.png
  android: true
  ios: true
  fullscreen: true

  android_12:
    image: assets/icon/splash_logo.png
    icon_background_color: "#ffffff"
    fullscreen: true
